### ISSUE TITLE
High load when haproxy is not running

### ISSUE THREAD

**Issue by jone** [4teamwork/supervisor-haproxy#4]
We've experienced high load ~~and many eventlistener processes~~ when the haproxy service is not running.
~~I suspect that the socket connection (eventlistener => haproxy) takes too long since there is no timet configured, leading to an unresponsive eventlistener process, leading to a new eventlistener process beeing spawned by haproxy.~~

**Comment by jone** [comment]
I could not really reproduce this locally.
@lukasgraf can you describe what exactly happened?

**Comment by jone** [comment]
I have noticed this behavior:
When haproxy is not running, the socket connection is refused, which leads to [a `FAIL` response](https://github.com/4teamwork/supervisor-haproxy/blob/master/supervisor_haproxy/event_listener.py#L68).
Supervisor will then [backof and rebuffer](http://supervisord.org/events.html#event-listener-notification-protocol) the event and send it later again.
This means the events are piling up, which could cause load.

I'm not sure what the best behavior is in this situation. I would like to put the eventlistener in an "error" state, but this is not supported by supervisor.
Responding with `FAIL` is correct from the eventlistener point of view, since it couldn't do the job, but it results in piled up events.

We could just result with `OK` and drop the event, so that we could avoid piled up events. But when we the connection is refused temporarily because of another problem it could lead to an instance beeing taken offline but never being put online again and we wouldn't notice.

Maybe best would be to `FAIL` for an amount of connection refused exceptions, and then switch to `OK` when the error persists, maybe after a given time..

**Comment by jone** [comment]
Correction: The effect is not having multiple processes but having high load because the events are requeued and reprocessed all the time..

**Comment by Rotonen** [comment]
@jone you managed to replicate this on a virtual machine. Did you already figure out what goes wrong there?

**Comment by jone** [comment]
@Rotonen yes, I could reproduce the problem easily by simply restarting an instance and waiting a bit. I have submitted a change in PR #5 which awoids the problem successfully.
